---
- name: Install PHP and required modules
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present
    update_cache: yes

- name: Restart Apache after PHP installation
  service:
    name: apache2
    state: restarted

